<script src="{{ asset('assets/js/jquery-3.2.1.min.js')}}"></script>
<script src="{{ asset('assets/css/bootstrap4/popper.js')}}"></script>
<script src="{{ asset('assets/css/bootstrap4/bootstrap.min.js')}}"></script>
<script src="{{ asset('assets/plugins/OwlCarousel2-2.2.1/owl.carousel.js')}}"></script>
<script src="{{ asset('assets/plugins/Isotope/isotope.pkgd.min.js') }}"></script>
<script src="{{ asset('assets/plugins/scrollTo/jquery.scrollTo.min.js') }}"></script>
<script src="{{asset('assets/plugins/easing/easing.js')}}"></script>
<script src="{{asset('assets/plugins/parallax-js-master/parallax.min.js')}}"></script>
<script src="{{asset('assets/js/custom.js')}}"></script>
